# Problema 4
_(Fonte: Linear Algebra and Its Applications. Addison-Wesley Longman, 1997)_

Suponha que uma economia consista nos setores de Carvão, Energia Elétrica e Aço, e a produção de cada setor
esteja distribuída entre os demais setores de acordo com a Tabela 1. A segunda coluna da Tabela 1 mostra 
que a produção de Energia Elétrica é distribuída da seguinte forma: 40% para Carvão, 50% para Aço e os restantes
10% para Energia Elétrica (Energia Elétrica considera esses 10% parte dos custos necessários para manter seu negócio). Determine os preços de equilíbrio, isto é, que tornam a receita de cada setor igual à sua despesa.

<img src="image1.png" width="500px" style="display: block; margin:auto" />
<center>Fonte: Adaptado de Linear Algebra and Its Applications. Addison-Wesley Longman, 1997.</center>





$$
A = 
\begin{bmatrix}
0.0 & 0.4 & 0.6 \\
0.6 & 0.1 & 0.2 \\
0.4 & 0.5 & 0.2 
\end{bmatrix}
=
\begin{bmatrix}
0 & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & \frac{1}{10} & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & \frac{2}{10}
\end{bmatrix}
$$

$$ 
A - \lambda =
\begin{bmatrix}
(0 - \lambda) & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & (\frac{1}{10} - \lambda) & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & (\frac{2}{10} - \lambda)
\end{bmatrix}
$$

$$ 
\begin{align*}
|A - \lambda I| &=
-\lambda \begin{vmatrix}
(\frac{1}{10}-\lambda) & \frac{2}{10} \\
\frac{5}{10} & (\frac{2}{10} - \lambda)
\end{vmatrix}

-\frac{4}{10} \begin{vmatrix}
\frac{6}{10} & \frac{2}{10} \\
\frac{4}{10} & (\frac{2}{10} - \lambda)
\end{vmatrix}

+ \frac{6}{10} \begin{vmatrix}
\frac{6}{10} & (\frac{1}{10} - \lambda) \\
\frac{4}{10} & \frac{5}{10}
\end{vmatrix}
\\

&= -\lambda^3 + \frac{3}{10}\lambda^2 + \frac{48}{100}\lambda + \frac{22}{100}

\end{align*}
$$


$$
-\lambda^3 + \frac{3}{10}\lambda^2 + \frac{48}{100}\lambda + \frac{22}{100} = 0 \\
\lambda = 1 \Rightarrow -1 + \frac{3}{10} + \frac{48}{100} + \frac{22}{100} = 0
$$

$$
\lambda = 1 \Rightarrow 
|A-\lambda I| = \begin{vmatrix}
-1 & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & \frac{-9}{10} & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & \frac{-8}{10}
\end{vmatrix}
$$

$$
(A - \lambda I)v = 0 \Leftrightarrow \begin{bmatrix}
-1 & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & \frac{-9}{10} & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & \frac{-8}{10}
\end{bmatrix}
\begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix}
=
0
$$

$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 1 \\
0 & 1 & 1
\end{bmatrix}

\begin{bmatrix}
1 & 0 & 0 \\
\frac{6}{10} & 1 & 0 \\
\frac{4}{10} & 0 & 1 
\end{bmatrix}

\begin{bmatrix}
-1 & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & \frac{-9}{10} & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & \frac{-8}{10}
\end{bmatrix}
=
\begin{bmatrix}
-1 & \frac{4}{10} & \frac{6}{10} \\
0 & \frac{-9}{10} & \frac{2}{10} \\
0 & \frac{5}{10} & \frac{-8}{10}
\end{bmatrix}

\begin{bmatrix}
-1 & \frac{4}{10} & \frac{6}{10} \\
0 & \frac{-9}{10} & \frac{2}{10} \\
0 & 0 & 0
\end{bmatrix}
$$



In [1]:
import numpy as np

A = np.array([
    [ 0.0, 0.4, 0.6 ],
    [ 0.6, 0.1, 0.2 ],
    [ 0.4, 0.5, 0.2 ]
])

# np.linalg.solve(A, [0.0, 0.0,0.0])
display(np.linalg.eig(A))
eigenv = np.linalg.eig(A)[1][:,0]*1.0

display(eigenv)
A@eigenv

(array([ 1.  +0.j        , -0.35+0.13228757j, -0.35-0.13228757j]),
 array([[ 0.58232009+0.j  , -0.47245559+0.25j, -0.47245559-0.25j],
        [ 0.52596653+0.j  ,  0.75592895+0.j  ,  0.75592895-0.j  ],
        [ 0.61988912+0.j  , -0.28347335-0.25j, -0.28347335+0.25j]]))

array([0.58232009+0.j, 0.52596653+0.j, 0.61988912+0.j])

array([0.58232009+0.j, 0.52596653+0.j, 0.61988912+0.j])

In [19]:
v = (np.array([308.0/330.0, -56.0/-66.0, 1.0])).astype(np.float128)
display(v)
A.astype(np.float128)@v

array([0.93333333, 0.84848485, 1.        ], dtype=float128)

array([0.93939394, 0.84484848, 0.99757576], dtype=float128)

In [5]:
A

array([[0. , 0.4, 0.6],
       [0.6, 0.1, 0.2],
       [0.4, 0.5, 0.2]])

In [9]:
import math
import numpy as np
import array_to_latex as altx

def proj(u,v):
    return (np.dot(u, v) / np.dot(u, u)) * u

def QR_decomp(A):
    u = []
    for i in range(A.shape[1]):
        u.append(
            A[:,i] - np.sum([ proj(u[j], A[:, i]) for j in range(i) ], axis=0 )
        )

    Q = np.array([u[i]/math.sqrt(np.dot(u[i],u[i])) for i in range(len(u))]).T

    R = []
    for i in range(A.shape[0]):
        R.append(
            [ np.dot(Q[:,i], A[:,j])*(1-max(0, min(i-j,1))) for j in range(A.shape[1]) ]
        )

    return Q, np.array(R)

In [68]:
# Nem sempre converge para todos autovalores, nem somente a parte real.
# Nesse caso A_[0,0] converge para um autovalor válido.
# Autovalores aproximados na diagonal principal.
# TODO: Pivotamento
# TODO: Matriz Hessenberg

def calcular_autovalores_qr(A):
    A_ = A.copy()
    for i in range(50000):
        Q, R = QR_decomp(A_)
        A_ = R@Q
    return A_.diagonal()

A_ = calcular_autovalores_qr(A)
A_

array([ 1.        , -0.31854204, -0.38145796])

In [72]:
# A - I*l_i
def subtrair_autovalor(A, l):
    return A-np.identity(A.shape[0])*l

A__ = subtrair_autovalor(A, A_[0])
A__

array([[-1. ,  0.4,  0.6],
       [ 0.6, -0.9,  0.2],
       [ 0.4,  0.5, -0.8]])

In [60]:
import scipy.linalg

def matriz_triangular_superior(A):
    return scipy.linalg.lu(A)[-1]

Ae = matriz_triangular_superior(A__)

In [73]:
# TODO: Generalizar
def substituicao_reversa(A):
    z = 1.0
    y = -Ae[1, -1]*z/Ae[1, -2]
    x = (-Ae[0, -1]*z -Ae[0,-2]*y)/Ae[0,0]
    return np.array([x, y, z])

x = substituicao_reversa(Ae)

In [75]:
display(x)
display(A@x)

array([0.93939394, 0.84848485, 1.        ])

array([0.93939394, 0.84848485, 1.        ])

In [84]:
def autovetores(A, i=0):
    A = A.copy()
    ls = calcular_autovalores_qr(A)
    A = subtrair_autovalor(A, ls[i])
    A = matriz_triangular_superior(A)
    return substituicao_reversa(A)
    
x = autovetores(A)
display(x)
display(A@x)

array([0.93939394, 0.84848485, 1.        ])

array([0.93939394, 0.84848485, 1.        ])