# Problema 4
_(Fonte: Linear Algebra and Its Applications. Addison-Wesley Longman, 1997)_

Suponha que uma economia consista nos setores de Carvão, Energia Elétrica e Aço, e a produção de cada setor
esteja distribuída entre os demais setores de acordo com a Tabela 1. A segunda coluna da Tabela 1 mostra 
que a produção de Energia Elétrica é distribuída da seguinte forma: 40% para Carvão, 50% para Aço e os restantes
10% para Energia Elétrica (Energia Elétrica considera esses 10% parte dos custos necessários para manter seu negócio). Determine os preços de equilíbrio, isto é, que tornam a receita de cada setor igual à sua despesa.

<img src="image1.png" width="500px" style="display: block; margin:auto" />
<center>Fonte: Adaptado de Linear Algebra and Its Applications. Addison-Wesley Longman, 1997.</center>





# Solução

O problema nos pede um ponto de equilíbrio no sistema gerado pela distribuição de produção de diferentes energias.
Um equilíbrio nesse contexto significa que os parâmetros do sistema são iguais ao seu resultado.

$$
Ax = x
$$

Observa-se pela definição acima que $A = I$, ou $A = 1$. O que significa que a transformação descrita pelo sistema
tem o efeito de uma multiplicação por escalar $\lambda = 1$ ao vetor $x$. Precisamos então encontrar $x$ para 
termos um valor de equilíbrio.

## Autovetores e Autovalores

Autovetores são vetores, diferentes de $0$, de uma transformação linear $T$, que têm seu valor aumentado por um fator 
$\lambda$ quando $T$ é aplicada a si. Isto é,
$$
T(x) = \lambda x
$$

Na equação acima, $\lambda$ é um autovalor, ou seja, um fator ao qual o autovalor é escalado.


O primeiro passo na obtenção dos autovetores de uma transformação linear é encontrar os seus autovalores.
Para isso, inicia-se buscando as raízes do polinômio característico definido pela determinante
$$
| A-\lambda I |
$$

Em seguida, para cada autovalor $\lambda_i$ encontrado, o vetor $v$ representa um autovetor no sistema
$$
(A-\lambda_i I)v = 0
$$

A matriz do problema tem os seguintes valores:

$$
A = 
\begin{bmatrix}
0.0 & 0.4 & 0.6 \\
0.6 & 0.1 & 0.2 \\
0.4 & 0.5 & 0.2 
\end{bmatrix}
=
\begin{bmatrix}
0 & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & \frac{1}{10} & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & \frac{2}{10}
\end{bmatrix}
$$

Como especificado antes, para encontrar os autovalores de $A$ calculamos as raízes do polinômio gerado por
 $\begin{vmatrix} A-\lambda I \end{vmatrix}$.

$$ 
A - I\lambda =
\begin{bmatrix}
(0 - \lambda) & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & (\frac{1}{10} - \lambda) & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & (\frac{2}{10} - \lambda)
\end{bmatrix}
$$

$$ 
\begin{align*}
|A - \lambda I| &=
-\lambda \begin{vmatrix}
(\frac{1}{10}-\lambda) & \frac{2}{10} \\
\frac{5}{10} & (\frac{2}{10} - \lambda)
\end{vmatrix}

-\frac{4}{10} \begin{vmatrix}
\frac{6}{10} & \frac{2}{10} \\
\frac{4}{10} & (\frac{2}{10} - \lambda)
\end{vmatrix}

+ \frac{6}{10} \begin{vmatrix}
\frac{6}{10} & (\frac{1}{10} - \lambda) \\
\frac{4}{10} & \frac{5}{10}
\end{vmatrix}
\\

&= -\lambda^3 + \frac{3}{10}\lambda^2 + \frac{48}{100}\lambda + \frac{22}{100}

\end{align*}
$$


Podemos observar que se $\lambda = 1$, a equação é satisfeita. Portanto, um de nossos autovalores é $1$.

$$
-\lambda^3 + \frac{3}{10}\lambda^2 + \frac{48}{100}\lambda + \frac{22}{100} = 0 \\
\lambda = 1 \Rightarrow -1 + \frac{3}{10} + \frac{48}{100} + \frac{22}{100} = 0
$$

Substituindo $\lambda$ por $1$ em $ \begin{vmatrix} A - \lambda I \end{vmatrix} $

$$
\lambda = 1 \Rightarrow 
|A-\lambda I| = \begin{vmatrix}
-1 & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & \frac{-9}{10} & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & \frac{-8}{10}
\end{vmatrix}
$$

E então resolvemos o sistema homogêneo abaixo através da elimiação gaussiana

$$
(A - \lambda I)v = 0 \Leftrightarrow \begin{bmatrix}
-1 & \frac{4}{10} & \frac{6}{10} \\
\frac{6}{10} & \frac{-9}{10} & \frac{2}{10} \\
\frac{4}{10} & \frac{5}{10} & \frac{-8}{10}
\end{bmatrix}
\begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix}
=
0
$$

e observamos que a matriz de coeficientes é singular, ou seja, possui 
colinearidade entre seus vetores coluna:

$$
\begin{bmatrix}
1 & 0 & -\frac{31}{33} & 0 \\
0 & 1 & -\frac{28}{33} & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}
$$

Logo, $z$ pode ser tratado como uma variável livre. Definindo $z = 1$ e substituindo

$$
z = 1 \\
y = \frac{28}{33} \\
x = \frac{31}{33} \\
$$

Pelo fato de autovetores terem a propriedade de serem apenas escalados pelo seu autovalor correspondente quando a
transformação de sua origem é aplicada à eles, podemos observar que o resultado é correto ao multiplicar a matriz
original pelo vetor coluna composto pelos valores encontrados

$$
\begin{bmatrix}
0.0 & 0.4 & 0.6 \\
0.6 & 0.1 & 0.2 \\
0.4 & 0.5 & 0.2 
\end{bmatrix}
\begin{bmatrix}
\frac{31}{33} \\ \frac{28}{33} \\ 1
\end{bmatrix}
=
\begin{bmatrix}
\frac{31}{33} \\ \frac{28}{33} \\ 1
\end{bmatrix}
$$

## Autovalores com Decomposição QR

É possível obter os autovalores de uma transformação linear através de um algoritmo iterativo. Iniciamos obtendo
a decomposição QR da matriz de entrada $A$ e em seguida repetimos as operações 
$$
Q, R := qr(A) \\
A := RQ
$$

Repetindo esse processo o suficiente, a diagonal principal de $A$ deve eventualmente convergir à parte real 
dos seus autovalores. Para uma descrição mais detalhada do método de decomposição QR, desenvolvemos uma explicação 
no problema 3.

### Implementação

In [67]:
# Importação das bibliotecas que iremos usar
import math
import scipy
import numpy as np

In [68]:
# Nem sempre converge para todos autovalores, nem somente a parte real.
# Nesse caso A_[0,0] converge para um autovalor válido.
# Autovalores aproximados na diagonal principal.
# TODO: Pivotamento
# TODO: Matriz Hessenberg

def calcular_autovalores_qr(A, n_iteracoes=5000):
    # Inicialmente copiamos a matriz
    # para que alterações se limitem
    # ao parâmetro.
    A_ = A.copy()

    # Em seguida iteramos n = 50000 vezes
    # as operações previamente definidas
    for i in range(n_iteracoes):

        # Usamos a função do scipy para calcular a decomposição QR.
        Q, R = scipy.linalg.qr(A_)
        A_ = R@Q

    # Os autovalores aproximados ficam na diagonal principal.
    return A_.diagonal()

## Definição do Sistema

In [107]:
# Definição da matriz do problema.
A = np.array([
    [ 0.0, 0.4, 0.6 ],
    [ 0.6, 0.1, 0.2 ],
    [ 0.4, 0.5, 0.2 ]
])
A

array([[0. , 0.4, 0.6],
       [0.6, 0.1, 0.2],
       [0.4, 0.5, 0.2]])

In [113]:
autovalores = calcular_autovalores_qr(A, n_iteracoes=10000)
autovalores

array([ 1.        , -0.34371361, -0.35628639])

In [112]:
# Podemos observar que a parte real dos autovalores se aproximam
# dos mesmos autovalores obtidos pela função da biblioteca numpy
np.linalg.eigvals(A)

array([ 1.  +0.j        , -0.35+0.13228757j, -0.35-0.13228757j])

In [114]:
# A - I*l_i
def subtrair_autovalor(A, l):
    return A-np.identity(A.shape[0])*l

# Agora subtraimos o autovalor da função inicial.
lambda_ = autovalores[0]
A_menos_l = subtrair_autovalor(A, lambda_)
A_menos_l

array([[-1. ,  0.4,  0.6],
       [ 0.6, -0.9,  0.2],
       [ 0.4,  0.5, -0.8]])

In [115]:
import scipy.linalg

def matriz_triangular_superior(A):
    # Retornamos apenas o U da fatoração LU.
    return scipy.linalg.lu(A)[-1]

Ae = matriz_triangular_superior(A_menos_l)
Ae.round(10)

array([[-1.  ,  0.4 ,  0.6 ],
       [ 0.  , -0.66,  0.56],
       [ 0.  ,  0.  , -0.  ]])

In [116]:
# Como a matriz obtida possui z variável,
# podemos fixar z em um valor, e obter
# os outros valores por substituição direta.

# Mudamos o último valor da matriz para 1 (z = 1)
Ae[-1,-1] = 1 
display(Ae)

# Criamos um vetor de variáveis independentes 
# onde o último coeficiente é 1.
b = np.zeros((Ae.shape[0], 1))
b[-1] = 1

# E resolvemos o sistema. 
# Nesse caso usamos a função solve do numpy,
# mas apenas por conveniência. É possível usar aqui
# também a função resolver_U já desenvolvida
# nos outros problemas.
x = np.linalg.solve(Ae, b)
x

array([[-1.  ,  0.4 ,  0.6 ],
       [ 0.  , -0.66,  0.56],
       [ 0.  ,  0.  ,  1.  ]])

array([[0.93939394],
       [0.84848485],
       [1.        ]])

In [119]:
# Podemos então verificar que x é de fato um autovetor.
display(x)
display(A@x)

array([0.93939394, 0.84848485, 1.        ])

array([0.93939394, 0.84848485, 1.        ])

In [121]:
# E escrever uma função que organiza os passos.
def autovetor(A, i=0):
    A  = A.copy()
    ls = calcular_autovalores_qr(A)
    A  = subtrair_autovalor(A, ls[i])
    A  = matriz_triangular_superior(A)
    return substituicao_reversa(A)
    
x = autovetor(A)
display(x)
display(A@x)

array([0.93939394, 0.84848485, 1.        ])

array([0.93939394, 0.84848485, 1.        ])

## Método da Potência


In [142]:
x0 = np.array([0.0, 0.0, 1.0])
Axk = A@x0
for i in range(25):
    Axk = A@Axk

#Ak = A**10
#Axk = Ak@x

display(Ak)
display(np.max(np.abs(Ak)))
max_Ak = np.max(np.abs(Ak))

xkm1 = 1/max_Ak * Axk 
display(xkm1)
display(A@xkm1)

xkm1norm = xkm1/ np.sqrt(np.dot(xkm1, xkm1))
display(xkm1norm)
display(A@xkm1norm)

array([[0.0000000e+00, 1.0485760e-04, 6.0466176e-03],
       [6.0466176e-03, 1.0000000e-10, 1.0240000e-07],
       [1.0485760e-04, 9.7656250e-04, 1.0240000e-07]])

0.006046617599999997

array([55.72644808, 50.33356601, 59.32170279])

array([55.72644808, 50.33356601, 59.32170279])

array([0.58232009, 0.52596653, 0.61988912])

array([0.58232009, 0.52596653, 0.61988912])